name: ledgerly_workspace
publish_to: none
environment:
  sdk: ^3.13.0
workspace:
  - packages/ledgerly_core
  - packages/ledgerly_data
  - app

hooks:
  user_defines:
    sqlite3:
      source: sqlcipher
